### ISSUE TITLE
I get an error and generates bad gifs or just crashes when trying to use example project

### ISSUE THREAD

**Issue by ghost** [jegor377/godot-gdgifexporter#17]
In the part where frames are added sometimes, it crashes or this error appears Invalid call. Nonexistent function 'is_alive' in base '_Thread'. with E 0:00:08.230   getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: nullptr

  <C++ Source>  ./core/rid.h:151 @ getornull())

**Comment by jegor377** [comment]
How to reproduce it? I tested example on Godot v3.5stable and it works fine.
![obraz_2022-08-21_222413810](https://user-images.githubusercontent.com/13947002/185809485-80d44c45-2502-4147-80ed-24f5fcd28add.png)

**Comment by ghost** [comment]
I didn't do anything to the example project but I tried the 3d version, not the 2d and it doesn't happen every time but a lot of times. Sometimes it works in multiple runs then it starts giving me the same error again.

**Comment by jegor377** [comment]
What is the 3D version? I tried it with Spatial and Camera3D and it works fine. :/
![obraz_2022-08-22_200405800](https://user-images.githubusercontent.com/13947002/185988743-464d7ef8-4083-4d35-9289-418b594bc607.png)

**Comment by ghost** [comment]
Never mind, I mixed up projects. It was my fault.
