### ISSUE TITLE
README example: Godot 4 FileAccess

### ISSUE THREAD

**Issue by LateNightIceCream** [jegor377/godot-gdgifexporter#19]
Hi :))

Godot 4 uses [FileAccess](https://docs.godotengine.org/en/stable/classes/class_fileaccess.html) instead of the `File` class to read/write files. The README example still mentions `File`. But the methods are the same so the name simply has to be changed in the README.

**Comment by LateNightIceCream** [comment]
made a PR!

**Comment by jegor377** [comment]
Thank you and sorry for replying so late! :D
