### ISSUE TITLE
Integration to Pixelorama

### ISSUE THREAD

**Issue by novhack** [jegor377/godot-gdgifexporter#5]
Hi,
I started integrating this repository to Pixelorama. I opened this issue to propose how I would like to proceed with integration.

My plan is to add a copy of folder `gdgifexporter` to folder `addons` in Pixelorama. There have been multiple issues with other submodule in Pixelorama so I would really like to avoid using that feature. I will of couse include the LICENCE.md file with it.

I will create a README.md file in `addons` where will be a name of this repository, author, version and link to github. Github will display this file directly to anyone browsing Pixeloramas code on Github. Similar to how it is in Godots repo: https://github.com/godotengine/godot/blob/master/thirdparty/README.md

If you have any issue with my proposal or you would like to integrate this repostory yourself I'm of course willing to step down a bit because I love what you did here. :)

**Comment by jegor377** [comment]
Feel free to implement it now as you said if you want. I am going to release this project propably with license header but I will think more about this later when it's done. Your idea is pretty good. 👍
