### ISSUE TITLE
Bug: Single color image export

### ISSUE THREAD

**Issue by novhack** [jegor377/godot-gdgifexporter#6]
I noticed that if I export an image with one solid color (it can be any color and alpha) the resulting gif is corrupted.
If such frame is inserted it between multiple frames of animation it will become fully transparent.
Just one aditional pixel in the image fixes the issue and different quantizations doesn't change the wrong result.
![single_color](https://user-images.githubusercontent.com/42614907/89107986-51443080-d435-11ea-8b2d-79941f93e87c.png)

**Comment by novhack** [comment]
Another bug that might be caused by the same issue is that if I export multiple frames which all have a transparent (0, 0, 0, 0) color in them then the resulting exported gif is also corrupted.

**Comment by jegor377** [comment]
I will look into that.

**Comment by jegor377** [comment]
I've fixed it in latest commit 13646d3d1fc5a77ed91bd62b69aa7e4c00c0a989
